quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/db
      driver: org.postgresql.Driver
    username: user
    password: password
  flyway:
    migrate-at-start: true
    locations: db/migration
  hibernate-orm:
    database:
      generation: none
  security:
    jwt:
      enabled: true
      auth-mechanism: jwt
  http:
    port: 9000
    cors:
      origins: "http://localhost:3000"
      methods: "GET, POST, PUT, DELETE"
      headers: "Content-Type, Authorization"
      access-control-allow-credentials: true

  native:
    resources:
      includes: publicVerificationKey.pem

mp:
  jwt:
    verify:
      publickey:
        location: publicVerificationKey.pem
        issuer: https://example.com/issuer

smallrye:
  jwt:
    sign:
      key:
        location: privateSigningKey.pem
